### ISSUE TITLE
Golang Test with segmentation violation

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#10]
I run test code below and got segmentation violation error in `m[res.StatusCode] += 1`.

```
...
type User struct {
	UserId   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
	UserPw   string `json:"userPw"`
}
type Usera struct {
	Name string
}

func init() {
	rand.Seed(time.Now().UnixNano())
}

var letterRunes = []rune("김이박최정강조윤장임한오서신권황안송류전홍고문양손배조백허유남심노정하곽성차주우구신임나전민유진지엄채원천방공강현함변염양변여추노도소신석선설마길주연방위표명기반왕금옥육인맹제모장남탁국여진어은편구용")
var letterRunes_name = []rune("가강건경고관광구규근기길나남노누다단달담대덕도동두라래로루리마만명무문미민바박백범별병보빛사산상새서석선설섭성세소솔수숙순숭슬승시신아안애엄여연영예오옥완요용우원월위유윤율으은의이익인일잎자잔장재전정제조종주준중지진찬창채천철초춘충치탐태택판하한해혁현형혜호홍화환회효훈휘희운모배부림봉혼황량린을비솜공면탁온디항후려균묵송욱휴언령섬들견추걸삼열웅분변양출타흥겸곤번식란더손술훔반빈실직흠흔악람뜸권복심헌엽학개롱평늘늬랑얀향울련")

const letterBytes_id = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

func RandStringBytes(n int, letterBytes string) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = letterBytes[rand.Intn(len(letterBytes))]
	}
	return string(b)
}

func RandStringRunes_firstname(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}
	return string(b)
}

func RandStringRunes_lastname(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letterRunes_name[rand.Intn(len(letterRunes_name))]
	}
	return string(b)
}

func worker(contexts *sync.Map, wg *sync.WaitGroup, requestURL string, jsonBody []byte, client *http.Client, transferRatePerSecond int, number_worker int) {
	defer wg.Done()
	fmt.Println("Threads start:", number_worker)
	// 로컬 맵 생성
	m := make(map[int]int)

	for i := 0; i < transferRatePerSecond; i++ {
		s := &User{
			UserId:   RandStringBytes(8, letterBytes_id),
			UserName: RandStringRunes_lastname(1) + RandStringRunes_firstname(2),
			Email:    RandStringBytes(5, letterBytes_id) + "@gmail.com",
			UserPw:   RandStringBytes(10, letterBytes_id),
		}
		buf, err := json.Marshal(s)
		if err != nil {
			log.Fatal(err)
			return
		}
		bodyReader := bytes.NewReader(buf)
		// 요청 생성
		req, err := http.NewRequest(http.MethodPost, requestURL, bodyReader)
		if err != nil {
			os.Exit(1)
		}

		// json 헤더 설정
		req.Header.Set("Content-Type", "application/json")

		// 실제 요청 전송 및 반환
		res, _ := client.Do(req)

		// 로컬 맵에 삽입
		m[res.StatusCode] += 1
	}

	for k, v := range m {
		result, ok := contexts.Load(k)
		if ok {
			contexts.Store(k, result.(int)+v)
		} else {
			contexts.Store(k, v)
		}
	}

}

func main() {

	argsWithoutProg := os.Args[1:]
	var wg sync.WaitGroup

	number_worker := 100
	// http 전송 url
	requestURL := argsWithoutProg[0]

	// json 파일 경로 ex) user
	// .json 확장자 명은 제외
	jsonReq := argsWithoutProg[1]

	// 실행횟수 설정
	transferRatePerSecond, _ := strconv.Atoi(argsWithoutProg[2])

	// JSON 파일 읽기
	jsonFile, err := os.Open(jsonReq + ".json")
	if err != nil {
		fmt.Println(err)
	}
	defer jsonFile.Close()

	t := http.DefaultTransport.(*http.Transport).Clone()
	t.MaxIdleConns = 10000    // connection pool 크기
	t.MaxConnsPerHost = 10000 // 호스트 별 최대 할당 connection
	t.MaxIdleConnsPerHost = 1

	// 클라이언트 설정 및 timeout
	client := &http.Client{
		Timeout:   1 * time.Second,
		Transport: t,
	}

	// json파일을 바이트로 변환
	jsonBody, _ := ioutil.ReadAll(jsonFile)

	// 스레드 싱크 맵
	var contexts = &sync.Map{}

	// 멀티 스레드 http request
	for i := 0; i < number_worker; i++ {
		wg.Add(1)
		go worker(contexts, &wg, requestURL, jsonBody, client, transferRatePerSecond/number_worker, i)
	}

	wg.Wait()

	// 성공한 http request 개수 확인
	contexts.Range(func(k, v interface{}) bool {
		fmt.Println("status: ", k, " count: ", v)
		return true
	})
}
```

**Comment by ghkdqhrbals** [comment]
# Solved

Its because I set my client timeout too short. After I change timeout 1 sec to 5 sec, it works properly.

```
client := &http.Client{
  Timeout:   5 * time.Second,
  Transport: t,
}
```

**Comment by ghkdqhrbals** [comment]
But, still segment violation occurs.

```
gyuminhwangbo@Gyuminui-MacBookPro testing % go run main.go http://localhost:8080/auth/user user 1000
Post "http://localhost:8080/auth/user": read tcp [::1]:60304->[::1]:8080: read: connection reset by peer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x121df34]

goroutine 679 [running]:
main.worker(0x0?, 0x0?, {0x7ff7bfeffba2, 0x1f}, {0x0?, 0x0?, 0x0?}, 0x0?, 0x1, 0x214)
	/Users/gyuminhwangbo/study/testing/main.go:93 +0xf4
created by main.main
	/Users/gyuminhwangbo/study/testing/main.go:150 +0x2a6
exit status 2
```

We have to focus on the `connection reset by peer` error message which nginx can handle a maximum of **512** concurrent connections.

The meaning of this error is that when we overload connection within same time, nginx cut off connection by themselves.

**So we need to think about what is the number of proper test threads, also the number of connections.**

// NGINX can handle a maximum of 512 concurrent connections. In newer versions, NGINX supports up to 1024 concurrent connections, by default.

**Comment by ghkdqhrbals** [comment]
In my opinion, the number of proper threads is 100 and max_sending_request will be 10K
