### ISSUE TITLE
PSQLException when user-server DB connection

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#26]
# Description

PSQLException when user-server DB connection

### Compose

```yaml
  user-db:
    container_name: user-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user
    expose:
      - "5435" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5435:5435" # Exposing 5435 to host machine
    volumes:
      - ./backups:/home/backups
    command: -c wal_level=logical -p 5435
    restart: always
```

### application.yaml

```yaml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user # Maybe this can be the main reason...
```

### Code

```
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:315) ~[postgresql-42.2.27.jar:42.2.27]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.2.27.jar:42.2.27]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.2.27.jar:42.2.27]
```

**Comment by ghkdqhrbals** [comment]
# Problem

As we check the error message below, **user-server still tempt to connect AWS-RDS** `database-1.cyykxhwims2n.ap-northeast-2.rds.amazonaws.com`

```
...
Caused by: java.net.UnknownHostException: database-1.cyykxhwims2n.ap-northeast-2.rds.amazonaws.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
...
```

# TODO
* Check configuration server that 
    * restart configuration server
    * send `busrefresh` to configuration server
