### ISSUE TITLE
[Bug] Spring Cloud Config Server 의 Git cloning 타임아웃 문제

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#320]
## **Description**

Spring-Cloud config server 는 git repo 를 clone 해서 여러 설정파일들을 읽습니다. 그리고 rabbitMQ 를 통해 다른 서비스들로 설정을 전파해줍니다. 그런데 git repo 를 clone 해오는데 주기적으로 타임아웃이 발생합니다. 😂😂

```
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/ghkdqhrbals/spring-chatting-server: connection failed
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:729) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:465) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:151) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1462) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        ... 85 common frames omitted
Caused by: java.net.ConnectException: Connect to github.com:443 [github.com/20.200.245.247] failed: Operation timed out github.com
        at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:240) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:654) ~[org.eclipse.jgit-6.4.0.202211300538-r.jar!/:6.4.0.202211300538-r]
        ... 90 common frames omitted
```

> 사실 굳이 Spring-Cloud configuration 서버를 사용하는 이유는 **실시간**으로 변경된 configuration 을 다른 서버들에게 반영해주고 싶었기 때문입니다. 만약 실시간으로 반복적으로 업데이트 하는 것이 아니라면 굳이 configuration 서버를 사용할 필요는 없습니다.
>
> 하지만, 제 설정에는 token-secret 이 있기 때문에 써야할 것 같습니다. 토큰의 경우 혹여나 탈취 될 수 있기때문에 실시간 및 주기적으로 업데이트해주는게 좋겠네요!

실제로 clone 하는 부분에서 문제가 발생했는지 확인하기 위해 아래의 명령어를 실행해보았습니다. 역시 clone 에서 timeout 이 발생했어요.

```
ubuntu@ip-172-31-8-39:~/test$ git clone git@github.com:ghkdqhrbals/spring-chatting-server.git
Cloning into 'spring-chatting-server'...
ssh: connect to host ssh.github.com port 443: Connection timed out
fatal: Could not read from remote repository.
```

**Comment by ghkdqhrbals** [comment]
**ec2 unbuntu 서버의 outbound 규칙까지 열어야 제대로 git clone 할 수 있었습니다!**
