### ISSUE TITLE
[TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block]

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#4]
When run elk stack, bump into this error.

```
kibana_1         | [2023-01-09T08:51:15.226+00:00][WARN ][plugins.usageCollection.usage-collection.usage-counters-service] ResponseError: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: cluster_block_exception: [cluster_block_exception] Reason: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:476:27)
kibana_1         |     at runMicrotasks (<anonymous>)
kibana_1         |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-client-server-internal/target_node/src/create_transport.js:58:16)
kibana_1         |     at ClientTraced.UpdateApi [as update] (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/update.js:50:12)
kibana_1         | [2023-01-09T08:51:15.230+00:00][WARN ][plugins.usageCollection.usage-collection.usage-counters-service] ResponseError: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: cluster_block_exception: [cluster_block_exception] Reason: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:476:27)
kibana_1         |     at runMicrotasks (<anonymous>)
kibana_1         |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-client-server-internal/target_node/src/create_transport.js:58:16)
kibana_1         |     at ClientTraced.UpdateApi [as update] (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/update.js:50:12)
kibana_1         | [2023-01-09T08:51:15.233+00:00][WARN ][plugins.usageCollection.usage-collection.usage-counters-service] ResponseError: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: cluster_block_exception: [cluster_block_exception] Reason: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:476:27)
kibana_1         |     at runMicrotasks (<anonymous>)
kibana_1         |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-client-server-internal/target_node/src/create_transport.js:58:16)
kibana_1         |     at ClientTraced.UpdateApi [as update] (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/update.js:50:12)
kibana_1         | [2023-01-09T08:51:15.237+00:00][WARN ][plugins.usageCollection.usage-collection.usage-counters-service] ResponseError: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: cluster_block_exception: [cluster_block_exception] Reason: index [.kibana_8.5.3_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:476:27)
kibana_1         |     at runMicrotasks (<anonymous>)
kibana_1         |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
kibana_1         |     at KibanaTransport.request (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-client-server-internal/target_node/src/create_transport.js:58:16)
kibana_1         |     at ClientTraced.UpdateApi [as update] (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/update.js:50:12)
```

**Comment by ghkdqhrbals** [comment]
# Solved

by add more disk space for docker container

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/29156882/211272112-d577cd8b-fa4d-45c7-a70a-201244ee9ecd.png">
